from __future__ import annotations

from typing import Mapping, Protocol


class UnsupportedBallSemantics(RuntimeError):
    """The injected runtime does not promise rigorous whole-ball inclusion."""


REQUIRED_SEMANTICS = (
    "supports_nonzero_radius",
    "outward_rounded",
    "native_entire_dirichlet_l",
    "whole_box_evaluation",
    "rigorous_complex_log",
)


class RigorousBallRuntime(Protocol):
    def complex_ball(self, real_lower: str, real_upper: str,
                     imag_lower: str, imag_upper: str) -> object: ...
    def pi_ball(self, precision_bits: int) -> object: ...
    def divide_exact_integer(self, numerator: int, denominator: object,
                             precision_bits: int) -> object: ...
    def real_log(self, value: object, precision_bits: int) -> object: ...
    def scale_and_shift_exponent(self, input_ball: object, log_base: object,
                                 precision_bits: int) -> object: ...
    def affine_half_plus_half(self, input_ball: object,
                              precision_bits: int) -> object: ...
    def complex_exp(self, value: object, precision_bits: int) -> object: ...
    def complex_gamma(self, value: object, precision_bits: int) -> object: ...
    def native_dirichlet_l(self, value: object, *, modulus: int,
                           conrey_number: int,
                           precision_bits: int) -> object: ...
    def multiply(self, *values: object, precision_bits: int) -> object: ...
    def rotate_complex_ball(self, value: object, real: str, imag: str,
                            precision_bits: int) -> object: ...
    def complex_log(self, value: object, precision_bits: int) -> object: ...
    def subtract(self, left: object, right: object,
                 precision_bits: int) -> object: ...
    def imaginary_interval(self, value: object) -> tuple[str, str]: ...
    def real_interval(self, value: object) -> tuple[str, str]: ...
    def sum_real_balls(self, values: object, precision_bits: int) -> object: ...
    def divide_by_two_pi(self, value: object, pi_ball: object,
                         precision_bits: int) -> object: ...
    def certifies_whole_box(self, value: object) -> bool: ...
    def certifies_principal_log(self, value: object) -> bool: ...
    def is_finite_ball(self, value: object) -> bool: ...
    def audit_ball_semantics(self) -> Mapping[str, bool]: ...


def audit_runtime_semantics(runtime: RigorousBallRuntime) -> None:
    semantics = runtime.audit_ball_semantics()
    if not isinstance(semantics, Mapping):
        raise UnsupportedBallSemantics("runtime semantics must be a mapping")
    missing = [name for name in REQUIRED_SEMANTICS if semantics.get(name) is not True]
    if missing:
        raise UnsupportedBallSemantics(
            "runtime lacks rigorous semantics: " + ", ".join(missing)
        )
