"""
T-04 wave-1 analysis — intrinsic only. No Athena / T-01 / T-03 comparison.
"""

from __future__ import annotations

import argparse
import json
import statistics
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Sequence, Tuple

ROOT = Path(__file__).resolve().parent.parent


def load_runs(path: Path) -> List[Dict[str, Any]]:
    out = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            if line.strip():
                out.append(json.loads(line))
    return out


def gkey(p: Dict[str, Any]) -> Tuple:
    return (p["N"], p["q"])


def analyze(runs: List[Dict[str, Any]]) -> Dict[str, Any]:
    by: Dict[Tuple, List[Dict[str, Any]]] = defaultdict(list)
    for r in runs:
        by[gkey(r["params"])].append(r)

    cells = []
    for key, recs in sorted(by.items()):
        dens = [r["density"] for r in recs]
        mg = [r["mean_gap_realized"] for r in recs]
        q = key[1]
        cells.append(
            {
                "N": key[0],
                "q": q,
                "n_seeds": len(recs),
                "density_mean": statistics.mean(dens),
                "density_std": statistics.pstdev(dens) if len(dens) > 1 else 0.0,
                "mean_gap_mean": statistics.mean(mg),
                "expected_density_approx": q,
                "expected_gap": 1.0 / q,
                "density_bias": statistics.mean(dens) - q,
            }
        )

    properties = [
        {
            "id": "N1",
            "name": "renewal_density_limit",
            "statement": (
                "For geometric gaps with success probability q, the long-run density of renewal "
                "points is q (elementary renewal theory: density = 1/E[G] = q)."
            ),
            "class": "NECESSARY",
            "justification": "Classical renewal reward / elementary renewal theorem on the integers.",
        },
        {
            "id": "N2",
            "name": "iid_gaps_no_local_field",
            "statement": (
                "Occupied set is generated by i.i.d. gaps; there is no synchronous neighborhood "
                "interaction (structurally not T-01/T-03 field dynamics)."
            ),
            "class": "NECESSARY",
            "justification": "By construction of the generator (spec 1.0).",
        },
        {
            "id": "N3",
            "name": "expected_gap",
            "statement": "E[G] = 1/q for geometric gaps as defined (trials until success).",
            "class": "NECESSARY",
            "justification": "Standard geometric distribution mean.",
        },
    ]

    # EMPIRICAL: density close to q
    biases = [abs(c["density_bias"]) for c in cells if c["N"] == 10000]
    if biases:
        properties.append(
            {
                "id": "E1",
                "name": "density_near_q_at_N10000",
                "statement": (
                    f"At N=10000, mean |density - q| across q-cells and seeds "
                    f"(cell-level |bias| mean) = {statistics.mean(biases):.4f}."
                ),
                "class": "EMPIRICAL",
                "justification": "Finite-N check of N1; not a new theorem.",
            }
        )

    # monotonic density in q
    # for fixed N, density_mean should increase with q
    mono_ok = 0
    mono_tot = 0
    for N in sorted({c["N"] for c in cells}):
        row = sorted([c for c in cells if c["N"] == N], key=lambda c: c["q"])
        mono_tot += 1
        if all(row[i]["density_mean"] < row[i + 1]["density_mean"] for i in range(len(row) - 1)):
            mono_ok += 1
    properties.append(
        {
            "id": "E2",
            "name": "density_increases_with_q",
            "statement": f"For {mono_ok}/{mono_tot} values of N, density_mean strictly increases with q.",
            "class": "EMPIRICAL",
            "justification": "Wave-1 observation; consistent with N1 but finite-N/seed.",
        }
    )

    volatile = [c for c in cells if c["density_std"] > 0.02]
    properties.append(
        {
            "id": "S1",
            "name": "seed_variance",
            "statement": f"{len(volatile)}/{len(cells)} cells have density_std > 0.02 across seeds.",
            "class": "SEED_DEPENDENT",
            "justification": "Finite-N renewal sampling variance.",
        }
    )

    properties.append(
        {
            "id": "U1",
            "name": "dependent_gaps_extension",
            "statement": "Behavior under non-i.i.d. gaps (Markov, long memory) — outside ola 1.",
            "class": "UNKNOWN",
            "justification": "Spec 1.0 is i.i.d. geometric only.",
        }
    )

    return {
        "family": "T-04",
        "spec_version": "1.0",
        "n_runs": len(runs),
        "n_param_cells": len(cells),
        "cells_summary": cells,
        "properties": properties,
        "note": "No Athena/T-01/T-03 bridge. No P* sealed.",
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw", type=Path, default=ROOT / "results" / "T04_REFERENCE_WAVE1" / "raw_runs.jsonl")
    ap.add_argument("--out", type=Path, default=ROOT / "results" / "T04_REFERENCE_WAVE1" / "analysis_wave1.json")
    args = ap.parse_args()
    report = analyze(load_runs(args.raw))
    args.out.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(
        json.dumps(
            {
                "n_runs": report["n_runs"],
                "n_param_cells": report["n_param_cells"],
                "properties": [{"id": p["id"], "class": p["class"], "name": p["name"]} for p in report["properties"]],
                "wrote": str(args.out),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
